### ISSUE TITLE
Where can i consume LSP4J Snapshot maven artifacts from

### ISSUE THREAD

**Issue by cdietrich** [eclipse-lsp4j/lsp4j#331]
hi, where can i consume LSP4J Snapshot maven artifacts from
ran 8 month ago the last time.
https://ci.eclipse.org/lsp4j/job/lsp4j-snapshots/
is that intended?

it would be nice to have a separate repo to consume from
(https://oss.sonatype.org/content/repositories/snapshots contains all kinds of snapshots, e.g. xtext too that we do not want to consume for the xtext builds)

**Comment by cdietrich** [comment]
(using tf jenkins does not work cause

```
Execution failed for task ':org.eclipse.xtext.ide:generateXtext'.
> Could not resolve all files for configuration ':org.eclipse.xtext.ide:compileClasspath'.
   > Could not resolve org.eclipse.lsp4j:org.eclipse.lsp4j:0.8.0-SNAPSHOT.
     Required by:
         project :org.eclipse.xtext.ide
      > Could not resolve org.eclipse.lsp4j:org.eclipse.lsp4j:0.8.0-SNAPSHOT.
         > Unable to load Maven meta-data from https://services.typefox.io/open-source/jenkins/job/lsp4j/job/master/lastSuccessfulBuild/artifact/build/maven-repository/org/eclipse/lsp4j/org.eclipse.lsp4j/0.8.0-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'https://services.typefox.io/open-source/jenkins/job/lsp4j/job/master/lastSuccessfulBuild/artifact/build/maven-repository/org/eclipse/lsp4j/org.eclipse.lsp4j/0.8.0-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'https://services.typefox.io/open-source/jenkins/job/lsp4j/job/master/lastSuccessfulBuild/artifact/build/maven-repository/org/eclipse/lsp4j/org.eclipse.lsp4j/0.8.0-SNAPSHOT/maven-metadata.xml'.
                  > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```)

**Comment by spoenemann** [comment]
https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/lsp4j/org.eclipse.lsp4j/

**Comment by cdietrich** [comment]
Unfortunately you cannot tell maven to consume lsp4j from there but Xtext not

**Comment by spoenemann** [comment]
That's a Maven problem, not LSP4J.

Alternative:
http://services.typefox.io/open-source/jenkins/job/lsp4j/job/master/lastStableBuild/artifact/build/maven-repository/

**Comment by cdietrich** [comment]
@spoenemann services typefox has a broken certificate chain

**Comment by cdietrich** [comment]
we created https://ci-staging.eclipse.org/xtext/job/lsp4j/ as a workaround

**Comment by robstryker** [comment]
Link doesn't work for me. "Application is not available. The application is currently not serving requests at this endpoint. It may not have been started or is still starting."

To be clear, I don't require this functionality, just trying to help triage / clean up old issues. 

Does typefox still have a broken chain? If not, this issue can be closed, no?
