### ISSUE TITLE
jsonrpc should de-structure byPosition array parameter of requests and notifications

### ISSUE THREAD

**Issue by testforstephen** [eclipse-lsp4j/lsp4j#553]
When i installed vscode-languageclient 7.0.0 to adopt LSP 3.16, i found there was a breaking change in languageclient@7.0.0 about adopting [Parameter Structures](https://www.jsonrpc.org/specification#parameter_structures) concept of jsonrpc@2.0, see [language client 7.0.0 changelog](https://github.com/Microsoft/vscode-languageserver-node#3160-protocol-600-json-rpc-700-client-and-700-server).

> * added support to control the [parameter structure](https://www.jsonrpc.org/specification#parameter_structures) when sending requests and notifications in `vscode-jsonrpc`. The parameter structure can be controlled using the additional `parameterStructures` argument when creating a request or notification type or when sending an untyped request or notification using the `sendRequest` or `sendNotification` function. The default is `ParameterStructures.auto` which does the following:
>    * use `byPosition` for messages with zero or greater than one parameter
>    * for one parameter it used `byName` for parameters which are object literals. Uses `byPosition` for all other parameters.

In summary, if the request/notification parameter is not an object parameter, jsonrpc will wrap it into an array. See [JSON_RPC](https://github.com/microsoft/vscode-languageserver-node/blob/faa68d90a976f158a8403a0f5cce54117ce61dbb/jsonrpc/src/common/connection.ts#L1065-L1083) implementation of language client.

Here are some samples of how to handle parameters in a language client jsonrpc.

- client.sendRequest(type, true)

   jsonrpc:
  {
   ...
   Params: [ true ]
  } 

- client.sendRequest(type, [true])

  jsonrpc:
  {
   ...
   Params: [ [ true ] ]
  }

- client.sendRequest(type, { value: true })

  jsonrpc:
  {
     ...
     Params: {
        value: true
    }
}

To avoid breaking in language server, jsonrpc in lsp4j should de-structure the outermost array wrapper if it‘s a single array parameter.

The code change is parseParams of MessageTypeAdapter.java. If the message parameter is an array, then flatten the array first and map each child item to the parameter type.

https://github.com/eclipse/lsp4j/blob/00447d0a44d75b03b6cebf3d2720a311411efdca/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/json/adapters/MessageTypeAdapter.java#L241-L251

**Comment by pisv** [comment]
For the record, the change in `vscode-languageserver-node` was introduced via the following commits: https://github.com/microsoft/vscode-languageserver-node/commit/182dfd85183ad42d626422fdb7907dca7fa8c2b0 and https://github.com/microsoft/vscode-languageserver-node/commit/a93e8b5ee26b7fb28245797adbdb0da585c0fb56.

**Comment by jonahgraham** [comment]
@testforstephen Is this an issue you are going to be able to provide the fix?

**Comment by testforstephen** [comment]
@jonahgraham sure, i can take a look.

**Comment by dhuebner** [comment]
@jonahgraham 
I've created a PR #714 to address this issue.

**Comment by dhuebner** [comment]
@jonahgraham 
Thanks for letting me know!
I fixed JsonRPC typos

**Comment by jonahgraham** [comment]
@dhuebner thanks for resolving the unwrap side. IIUC there is a wrap side to do? I see you have some WIP in https://github.com/eclipse-lsp4j/lsp4j/commit/21cb96a1f488ffe86252858912abea03c579f1fc?

**Comment by dhuebner** [comment]
@jonahgraham 
Yes, I started working on this one too. I'm not quite sure in some cases and need a bit more time to finish it.
Especially not clear to me is how to identify that the argument being passed is a JS primitive or an array. Any comments or re-view upfront in [this branch](https://github.com/eclipse-lsp4j/lsp4j/tree/dh-wrap-param) are very welcome. 
See also [here](https://github.com/eclipse-lsp4j/lsp4j/commit/21cb96a1f488ffe86252858912abea03c579f1fc#diff-5e45d4399e1212a7e8d7fe400f218d8536160862b0fe49a282982d02ffbd903bR463)

**Comment by jonahgraham** [comment]
Thank @dhuebner  - I will have a look at it next week.

**Comment by jonahgraham** [comment]
I think this is done - but I think needs an entry in the Changelog as this behaviour change could be unexpected.

**Comment by jonahgraham** [comment]
> I think this is done - but I think needs an entry in the Changelog as this behaviour change could be unexpected.

Done in #731
