### ISSUE TITLE
Support new DAP `startDebugging` request

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-lsp4j/lsp4j#662]
See https://github.com/microsoft/debug-adapter-protocol/issues/79 and https://github.com/microsoft/debug-adapter-protocol/pull/326

**Comment by KamasamaK** [comment]
That request was removed from the spec for now, so I've removed it from #663 and I don't think it will make LSP4J v0.16.

See microsoft/debug-adapter-protocol#334

**Comment by mickaelistria** [comment]
@KamasamaK Coming back to this topic, are you aware of any external blocker before we can add support for startDebugging in LSP4J DAP support?

**Comment by mickaelistria** [comment]
Submitted https://github.com/eclipse/lsp4j/pull/704 that hopefully does the job as expected...

**Comment by jonahgraham** [comment]
Fixed in #704 (with the rest of DAP 1.60.0 in #716)
