### ISSUE TITLE
Support for workspace.fileOperatioms

### ISSUE THREAD

**Issue by asmodeus812** [eclipse-lsp4j/lsp4j#735]
Hi, i was looking through the implementation and noticed that most of the workspace file ops return unsupported exception. Is there a plan to add support for the willRename,Create,Delete ops ? Thanks !

**Comment by pisv** [comment]
Hi, these methods are intended to be implemented by specific language servers, not by LSP4J itself. They throw UOE by default because it is up to a language server to implement them or not; they are not required to be implemented by all language servers according to the spec.

**Comment by asmodeus812** [comment]
Ah okay i seee,  i will then make sure to ask in jdtls. Thanks i will close this one.
