### ISSUE TITLE
Invalid generation of @JsonRpcData when using lsp4j 0.21 and xtend 2.31.0

### ISSUE THREAD

**Issue by dvojtise** [eclipse-lsp4j/lsp4j#742]
When installing lsp4j and xtend from the current Eclipse release update site (2023-06) It installs lspj4 0.21.0 and xtend 2.31.0

(I started from Eclipse Modeling 2023-06 and then installed lsp4j using the updatesite https://download.eclipse.org/releases/2023-06/ )

A simple project using @JsonRpcData from lsp4j.generator will now fail.  The generated java class is incorrect. (the toString 

```java
package bug_lsp4j_xtend

import org.eclipse.lsp4j.generator.JsonRpcData

@JsonRpcData
class MyAnnotatedClass {
	
}
```

will generate a code that doesn't compile
![image](https://github.com/eclipse-lsp4j/lsp4j/assets/661468/2a077e84-215c-4e4f-9e80-74098a11c19e)

An equivalent code was working in the previous release I tried (xtend 2.25.0 + lsp4j 0.14.0)  (I haven't tried yet to find the exact last working version ...)

project showing the issue joined
[bug_lsp4j_xtend_2023-06.zip](https://github.com/eclipse-lsp4j/lsp4j/files/11785481/bug_lsp4j_xtend_2023-06.zip)

**Comment by cdietrich** [comment]
how does your manifest look like? package import? require bundle?

**Comment by cdietrich** [comment]
you dont have a dependency to lsp4j itself? is this intentional?

**Comment by dvojtise** [comment]
I mainly need to use the same approach as lsp4j in order to generate similar protocols. JSONRPC based  but neither DAP nor LSP. (your jsonrpc lib is cool ;-) )


I added several of the other bundles in the dependencies, without better result on this example.

**Comment by cdietrich** [comment]
simply copy the ToStringBuilder class to xxx.util package

**Comment by dvojtise** [comment]
Thanks, it works

I'll update my projects with that

**Comment by dvojtise** [comment]
BTW, I second your proposal about moving the ToStringBuilder class since I haven't seen https://github.com/eclipse-lsp4j/lsp4j/blob/main/org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/util/ToStringBuilder.java any differences between 
and
https://github.com/eclipse-lsp4j/lsp4j/blob/main/org.eclipse.lsp4j.debug/src/main/java/org/eclipse/lsp4j/debug/util/ToStringBuilder.java

**Comment by cdietrich** [comment]
yes it is the same, but we dont have a util place that is available from both

**Comment by jonahgraham** [comment]
> @jonahgraham maybe we should move the ToStringBuilder class to jsonrpc module? 

Yes that makes sense. The generator makes code that works with jsonrpc, so having the ToStringBuilder in (e.g.) new `package org.eclipse.lsp4j.jsonrpc.util` makes sense to me.

> the problem is this is not a runtime dependency

Sorry, I don't know what you mean here? Does this mean that `org.eclipse.lsp4j.jsonrpc` is not a runtime dep of the generator? Is it a problem adding it?

**Comment by cdietrich** [comment]
@jonahgraham no its not a dependency of lsp4j itself. so it wont work at runtime

**Comment by jonahgraham** [comment]
The same problem occurs with the less often used reference to Preconditions.

**Comment by pisv** [comment]
> The same problem occurs with the less often used reference to Preconditions.

Looks like it would make sense to handle it in the same way, after #798 is merged.
