### ISSUE TITLE
Implement default behavior for stepIn and stepOut to nextStep

### ISSUE THREAD

**Issue by apupier** [eclipse-lsp4j/lsp4j#743]
Based on [specification for Step In](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_StepIn), `If the request cannot step into a target, stepIn behaves like the next request.`.

Currently, by default the `IDebugProtocolServer.stepIn` [method](https://github.com/eclipse-lsp4j/lsp4j/blob/e32c63b7b1cea5b777bd0d99c4045f4932ad3ff7/org.eclipse.lsp4j.debug/src/main/java/org/eclipse/lsp4j/debug/services/IDebugProtocolServer.java#L390) is throwing an `UnsupportedOperationException`

I think it could be convenient that it redirect to nextStep by default so that the specification is fulfilled immediately without the client required to implement it

**Comment by jonahgraham** [comment]
Please see my comment on the associated PR https://github.com/eclipse-lsp4j/lsp4j/pull/744#issuecomment-1778058253

For the same reasons I am closing this issue.
