### ISSUE TITLE
org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation

### ISSUE THREAD

**Issue by D0zee** [eclipse-lsp4j/lsp4j#756]
Hello everyone! I write a language server for kotlin build scripts. I've started get warnings from lsp4j as I understand on client side. 

The example of a such warning is below:
`2023 7:17:07 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 7`

What does this warning mean? And how to fix it? 
My lsp4j version on server side is 0.15.0, on client side as I suspect is latest, because I use lsp4j as a dependency in eclipse plugin. I've already tried to increase the version of lsp4j on server side, but nothing helps.

**Comment by jonahgraham** [comment]
> What does this warning mean? 

I think it means that the client is sending a cancel to the server for a message that it never to the server in the first place, or perhaps client sent a cancel after the server already replied. If it is the former, that sounds like a client bug, if it is the latter that is probably a race condition.

> And how to fix it?

I don't think updating the server to latest will make much of difference as I don't think LSP4J has made changes recently, have a look at the [changelog](https://github.com/eclipse-lsp4j/lsp4j/blob/main/CHANGELOG.md). 

If the client is LSP4E perhaps some of the relatively new cancellation support isn't lining up with the server expectation.

Can you share a more complete log of the messages?

**Comment by D0zee** [comment]
These two lines are full log message. This warning appears when on any edits of file. I thought that maybe error from my end, but I went to older commits and the warning appears there also, althought I didn't see this warning in my log before.

**Comment by jonahgraham** [comment]
> These two lines are full log message

Sorry, too many meanings for log around :) I meant the full log of the communication between client and server, the json-rpc contents.

**Comment by D0zee** [comment]
https://pastebin.com/TvWKji3C
It's full log of communication between server and client.  But there are strange logs - it's just for debugging. The test project is a simple application from `gradle init`. After full initialization (I noted the end of it), I typed one character at a time and looked at the logs

**Comment by jonahgraham** [comment]
Sorry that is still the workspace log, I am talking about the log showing all the JSON-RPC objects back and forth. You can turn that on in LSP4E in this preference pace:

![image](https://github.com/eclipse-lsp4j/lsp4j/assets/679236/0cd02a23-23ad-4a84-a5cf-3373cdc8c29f)

and then in the Console (or file you logged to) you will see all the JSON-RPC back and forth:

![image](https://github.com/eclipse-lsp4j/lsp4j/assets/679236/94a77c65-b4bc-4a74-8cd3-527999b5e4b1)

In that log you can track down what is happening by finding the messages with the matching IDs, e.g. `{"jsonrpc":"2.0","id":"7"`

**Comment by jonahgraham** [comment]
PS LSP4E is being improved all the time and there is some initiatives to provide better logging UIs. See for example https://github.com/eclipse/lsp4e/issues/745

**Comment by D0zee** [comment]
Hello, I return with logs. These logs are printed on one change in text file.


```
[t=1692356789408] LSP4E to org.eclipse.buildship.kotlinDSL.provider.server:
Content-Length: 346



[t=1692356789410] LSP4E to org.eclipse.buildship.kotlinDSL.provider.server:
{"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"version":13,"uri":"file:///Users/kolavladimirov/Downloads/sample_composite_builds_basics-kotlin-dsl-2/my-utils/string-utils/build.gradle.kts"},"contentChanges":[{"range":{"start":{"line":16,"character":1},"end":{"line":16,"character":1}},"rangeLength":0,"text":"f"}]}}

[t=1692356789675] org.eclipse.buildship.kotlinDSL.provider.server to LSP4E:
{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"debounce0 Linting .../string-utils/build.gradle.kts"}}

[t=1692356789685] org.eclipse.buildship.kotlinDSL.provider.server to LSP4E:
{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":2,"message":"compiling [KtFile: /Users/kolavladimirov/Downloads/sample_composite_builds_basics-kotlin-dsl-2/my-utils/string-utils/build.gradle.kts] with BUILD_SCRIPT"}}

[t=1692356789902] LSP4E to org.eclipse.buildship.kotlinDSL.provider.server:
Content-Length: 65



[t=1692356789902] LSP4E to org.eclipse.buildship.kotlinDSL.provider.server:
{"jsonrpc":"2.0","method":"$/cancelRequest","params":{"id":"29"}}

[t=1692356789902] LSP4E to org.eclipse.buildship.kotlinDSL.provider.server:
Content-Length: 224



[t=1692356789902] LSP4E to org.eclipse.buildship.kotlinDSL.provider.server:
{"jsonrpc":"2.0","id":"31","method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///Users/kolavladimirov/Downloads/sample_composite_builds_basics-kotlin-dsl-2/my-utils/string-utils/build.gradle.kts"}}}

[t=1692356789908] org.eclipse.buildship.kotlinDSL.provider.server to LSP4E:
{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":2,"message":"client    Unmatched cancel notification for request id 29"}}

[t=1692356789909] org.eclipse.buildship.kotlinDSL.provider.server to LSP4E:
{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"async2    Find symbols in .../string-utils/build.gradle.kts"}}

[t=1692356789910] org.eclipse.buildship.kotlinDSL.provider.server to LSP4E:
{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"async2    Finished in 1 ms"}}

[t=1692356789911] org.eclipse.buildship.kotlinDSL.provider.server to LSP4E:
{"jsonrpc":"2.0","id":"31","result":[]}

[t=1692356789977] LSP4E to org.eclipse.buildship.kotlinDSL.provider.server:
Content-Length: 264



[t=1692356789977] LSP4E to org.eclipse.buildship.kotlinDSL.provider.server:
{"jsonrpc":"2.0","id":"32","method":"textDocument/documentHighlight","params":{"textDocument":{"uri":"file:///Users/kolavladimirov/Downloads/sample_composite_builds_basics-kotlin-dsl-2/my-utils/string-utils/build.gradle.kts"},"position":{"line":16,"character":2}}}

[t=1692356789982] org.eclipse.buildship.kotlinDSL.provider.server to LSP4E:
{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"async2    Re-parsing build.gradle.kts 0:1-19:1"}}

[t=1692356790060] org.eclipse.buildship.kotlinDSL.provider.server to LSP4E:
{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///Users/kolavladimirov/Downloads/sample_composite_builds_basics-kotlin-dsl-2/my-utils/string-utils/build.gradle.kts","diagnostics":[]}}

[t=1692356790077] org.eclipse.buildship.kotlinDSL.provider.server to LSP4E:
{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///Users/kolavladimirov/Downloads/sample_composite_builds_basics-kotlin-dsl-2/my-utils/string-utils/build.gradle.kts","diagnostics":[{"range":{"start":{"line":16,"character":0},"end":{"line":16,"character":2}},"severity":1,"code":"UNRESOLVED_REFERENCE","source":"kotlin","message":"Unresolved reference: ff","tags":[]}]}}

[t=1692356790082] org.eclipse.buildship.kotlinDSL.provider.server to LSP4E:
{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"debounce0 Reported 1 diagnostics in .../string-utils/build.gradle.kts"}}

[t=1692356790083] org.eclipse.buildship.kotlinDSL.provider.server to LSP4E:
{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"async2    Hovering BLOCK"}}

[t=1692356790083] org.eclipse.buildship.kotlinDSL.provider.server to LSP4E:
{"jsonrpc":"2.0","id":"32","result":[]}
```

**Comment by jonahgraham** [comment]
Higher up the log is there a request with ID 29 (the ID that the cancel was for)? Is there a response from that request?

**Comment by D0zee** [comment]
I think that this request doesn't get a response, because It doesn't influence on something, just appears

**Comment by D0zee** [comment]
You are right, it was method that worked wrongly. I turned off it and warnings disappeared.

**Comment by jonahgraham** [comment]
I am glad to know you have managed to figure it out. Thanks for reporting back and closing the issue.

**Comment by xiaocaiji007** [comment]
Hello everyone! I also encountered the same problem, but I didn't understand how you solved it

**Comment by cdietrich** [comment]
@xiaocaiji007 did you check the request log? which client do you use?

**Comment by xiaocaiji007** [comment]
I have built an online editor using monaco editor.
I found that the server has already responded, but still received a cancellation request. Does this mean that there is a problem with the client?

**Comment by cdietrich** [comment]
might be. but maybe the server should also be more lenient with that.
