### ISSUE TITLE
Builds failing on Jenkins

### ISSUE THREAD

**Issue by pisv** [eclipse-lsp4j/lsp4j#760]
Since Aug 16, builds started to fail on Jenkins with the following error both for `main` and `release_0.21` branches:

`[ERROR]     Unresolveable build extension: Plugin org.eclipse.tycho:tycho-maven-plugin:2.7.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.eclipse.tycho:tycho-maven-plugin:jar:2.7.5: The following artifacts could not be resolved: org.eclipse.tycho:tycho-maven-plugin:pom:2.7.5 (absent): Could not transfer artifact org.eclipse.tycho:tycho-maven-plugin:pom:2.7.5 from/to cbi (https://repo.eclipse.org/content/repositories/cbi-releases/): status code: 403, reason phrase: Forbidden (403)`

For details, see https://ci.eclipse.org/lsp4j/job/lsp4j-multi-build/job/main/115/console and https://ci.eclipse.org/lsp4j/job/lsp4j-multi-build/job/release_0.21/3/console.

**Comment by cdietrich** [comment]
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3560#note_1198035
?

**Comment by pisv** [comment]
@cdietrich Thanks for pointing it out!

I've just rerun the builds and they are green now.

**Comment by cdietrich** [comment]
wonder if we need to do something like https://chat.eclipse.org/#/room/#modeling-emf-mwe-builds:matrix.eclipse.org

**Comment by pisv** [comment]
Yes, I also wondered why there were no notifications about build failures... It would have been great to have such a mechanism in place.

**Comment by cdietrich** [comment]
@jonahgraham (as this needs pl approval) what do you think (if you agree i can open the helpdesk ticket and pr)

**Comment by jonahgraham** [comment]
+1

**Comment by cdietrich** [comment]
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3564

**Comment by pisv** [comment]
@cdietrich Thank you for moving it forward!
