### ISSUE TITLE
Do we need to cancel `listener` on `exit`?

### ISSUE THREAD

**Issue by tdroxler** [eclipse-lsp4j/lsp4j#770]
Hi everyone,

quick question, I'm starting my server with the `startListening` function and get back the `Future[Void]`. When my server receive the `exit` notification (after the obvious `shutdown`), do I need to `cancel` or clean in any other way my `listnener` (the `Future[Void]`)?

Thx

**Comment by pisv** [comment]
Hi @tdroxler,

You need to call `cancel(true)` on the future to close the `StreamMessageProducer`, which will break the loop in the `StreamMessageProducer.listen` method.

https://github.com/eclipse-lsp4j/lsp4j/blob/3c98376797b96922689af963b8403431135f0f35/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/json/ConcurrentMessageProcessor.java#L69-L78

HTH

**Comment by pisv** [comment]
See also #585.

**Comment by tdroxler** [comment]
Thx for your quick answer, I guess I'll go with something like (pseudo code and `scala`):

```
  override def exit(): Unit = {
    server.listener.cancel(true)
    if(server.shutdownReceived) {
      System.exit(0)
    } else {
      System.exit(1)
    }
  }
```

checking the `shutdownReceived` to follow the [exit specs](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#exit)

**Comment by pisv** [comment]
LGTM 👍
