### ISSUE TITLE
only Jar Files 

### ISSUE THREAD

**Issue by sho94os** [eclipse-lsp4j/lsp4j#774]
i want to use lsp4j in my projekt that not use Maven. i just want to take the jar files of lsp4j and add it to my projekt. how i can download this jar file

**Comment by cdietrich** [comment]
download from maven central?

**Comment by pisv** [comment]
Alternatively, you can download a zip with jars, which is a zipped p2-site technically. You can use the following link for the latest release: https://download.eclipse.org/lsp4j/updates/releases/0.21.1/v0.21.1.zip.

There are also download links for each release: https://github.com/eclipse-lsp4j/lsp4j/releases.
