### ISSUE TITLE
Upgrade to recent BND

### ISSUE THREAD

**Issue by laeubi** [eclipse-lsp4j/lsp4j#776]
A recent discussion in OSGi-WG channels has shown that lsp4j uses bnd plugin in a "deprecated way", as I'm not familar enough with gradle I can only copy some instructions here that might be usefull for the maintainers of this project to upgrade given by @bjhargrave:

> They are also using the bnd plugin in the old deprecated way. It should be jar.bundle.bnd and not jar.bnd. That is, the bnd DSL element has moved under the bundle DSL element. See https://github.com/bndtools/bnd/wiki/Changes-in-6.0.0#bnd-gradle-plugins for the bullet about gradle deprecation of conventions.

**Comment by cdietrich** [comment]
from that page you linked i cannot derive anything.

**Comment by cdietrich** [comment]
we also use more stuff that is deprecated in newer gradle versions

**Comment by cdietrich** [comment]
is anyone using the gradle ide task?

**Comment by cdietrich** [comment]
new bnd needs j17 to run build

**Comment by jonahgraham** [comment]
> is anyone using the gradle ide task? does anyone know how to use it?

Does this refer to the contents of https://github.com/eclipse-lsp4j/lsp4j/tree/db27a95ff71f6892074df6c404560c05f55552bc/ide ? If so, I don't think anyone is using them, if they are the references in them are really out of date. The underlying gradle plug-in is also ["mostly abandoned"](https://github.com/diffplug/goomph?tab=readme-ov-file#ide-as-build-artifact-this-part-is-mostly-abandoned) (https://github.com/diffplug/goomph/issues/189) so I think we can remove it without further thought.

![image](https://github.com/eclipse-lsp4j/lsp4j/assets/679236/aaa79f9d-45b0-48c5-88f0-39c241ff1ee1)

**Comment by jonahgraham** [comment]
> > is anyone using the gradle ide task? does anyone know how to use it?
> 
> Does this refer to the contents of https://github.com/eclipse-lsp4j/lsp4j/tree/db27a95ff71f6892074df6c404560c05f55552bc/ide ? [...]

Removed in #794

**Comment by cdietrich** [comment]
nice

**Comment by jonahgraham** [comment]
#781 modernizes gradle usage (thanks @cdietrich for doing the heavy lifting)

> new bnd needs j17 to run build

Because of this we are not at this time upgrading to bnd 7
