### ISSUE TITLE
Build failing on `main`

### ISSUE THREAD

**Issue by pisv** [eclipse-lsp4j/lsp4j#779]
I have noticed that `lsp4j-multi-build` failed on `main` after merging PR #777:
https://ci.eclipse.org/lsp4j/job/lsp4j-multi-build/job/main/124/console.

This seems to be caused by an issue with gpg signing:

```
17:53:48  gpg: no default secret key: Unusable secret key
17:53:48  gpg: signing failed: Unusable secret key
```

**Comment by jonahgraham** [comment]
@pisv can you raise a helpdesk ticket, I assume that webmaster needs to fix our keys https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/new

**Comment by pisv** [comment]
@jonahgraham Thank you for the hint!

I have opened https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4098.

**Comment by pisv** [comment]
The issue has been fixed: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4098#note_1568148.
