### ISSUE TITLE
ResponseErrorException is not propagated with the default exception handler

### ISSUE THREAD

**Issue by ivy-cst** [eclipse-lsp4j/lsp4j#802]
The same as: https://github.com/eclipse-lsp4j/lsp4j/issues/576
But by then only the doc had changed: https://github.com/eclipse-lsp4j/lsp4j/pull/578

In my opinion this is not very user friendly. If I bother to throw a `ResponseErrorException`, it should be propagated even if it is thrown when the method is called and not only when the `CompletableFuture` is executed.

As an example, we do check some context stuff that is only available as a `ThreadLocal` and not while the `CompletableFuture` is executed.

There is also an open source example on [eclpse-gslp](https://github.com/eclipse-glsp/) that does this incorrectly. See [DefaultGLSPServer](https://github.com/eclipse-glsp/glsp-server/blob/2bb9e0b545f9f2657b26c8526f16a40ef5d2228e/plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/protocol/DefaultGLSPServer.java#L77)

**Comment by jonahgraham** [comment]
Can I confirm that the use case you are seeing is that you are getting the "wrong" `ResponseError` back? Instead of getting the `ResponseError` with the code, message and data that you expect you are getting an `Internal error` message/code and the data is the stack trace?

**Comment by ivy-cst** [comment]
> Can I confirm that the use case you are seeing is that you are getting the "wrong" `ResponseError` back? Instead of getting the `ResponseError` with the code, message and data that you expect you are getting an `Internal error` message/code and the data is the stack trace?

Yes a new `ResponseError` is generated and even worse the exception is logged as `SEVERE` here: https://github.com/eclipse-lsp4j/lsp4j/blob/88868d3506d317b12cf0bfd1e82a254489f8c47b/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/RemoteEndpoint.java#L62

**Comment by jonahgraham** [comment]
> Yes a new `ResponseError` is generated [...]

Thanks for confirming. I think that the PR I provided will resolve this case. Thanks for pointing out the secondary problem of the SEVERE log message too.
