### ISSUE TITLE
Position's line and character fields should be long, not int

### ISSUE THREAD

**Issue by shuheiktgw** [eclipse-lsp4j/lsp4j#823]
Currently, [the Position's line and character fields are int](https://github.com/eclipse-lsp4j/lsp4j/blob/cc20058d5b3d58596d49b71ca3c20308cc451844/org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/Protocol.xtend#L5325), but according to the latest protocol definition, the fields should be uinteger, which can be 0 to 2^31 - 1. Therefore, I believe they should have been long 🙂 

- https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#position
- https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#baseTypes

**Comment by nixel2007** [comment]
Integer covers this range as well: https://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html

**Comment by shuheiktgw** [comment]
@pisv Wait why? IIUC, the Integer class mentioned above is different from int. int is 32-bit signed integer, so maximum value is not 2^31 - 1 but 2^30.

**Comment by shuheiktgw** [comment]
Ah sorry, I must have misunderstood something. Let me think about it...

**Comment by nixel2007** [comment]
int also uses the same boundaries :)

https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html

**Comment by shuheiktgw** [comment]
Yes, sorry I miscalculated that 🙇
