### ISSUE TITLE
Add `keepWhitespace` option to CompletionItem

### ISSUE THREAD

**Issue by sdaimwood** [eclipse-lsp4j/lsp4j#844]
Hi there,

In 2018 the LSP protocol added a `keepWhitespace` option for CompletionItems to preserve whitespace and not add automatic indentation on subsequent lines based on where the completion was prompted from. See [this issue](https://github.com/microsoft/vscode/issues/62057) and the implementation [here](https://github.com/microsoft/vscode/blob/3b37bcdc19a293e8e6c32ff991a67031ff73340d/src/vscode-dts/vscode.d.ts#L4993-L4998). 

A language server I help maintain would greatly benefit from being able to use that setting if it can be added to the LSP4J `CompletionItem` as well.

**Comment by cdietrich** [comment]
https://github.com/microsoft/language-server-protocol/issues/83
https://github.com/eclipse-lsp4j/lsp4j/blob/f235e91fbe2e45f62e185bbb9f6d21bed48eb2b9/org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/InsertTextMode.java#L29

**Comment by sdaimwood** [comment]
> [microsoft/language-server-protocol#83](https://github.com/microsoft/language-server-protocol/issues/83)
> 
> https://github.com/eclipse-lsp4j/lsp4j/blob/f235e91fbe2e45f62e185bbb9f6d21bed48eb2b9/org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/InsertTextMode.java#L29

Thank you! I was looking for exactly this but looks like we were too far behind on our lsp4j version, working on getting up to date now.
