### ISSUE TITLE
Mismatched `FileChangeType` enum values

### ISSUE THREAD

**Issue by Papierkorb2292** [eclipse-lsp4j/lsp4j#851]
The `FileChangeType` enum of lsp4j uses the following three values: `Created(1), Changed(2), Deleted(3)` (see https://github.com/eclipse-lsp4j/lsp4j/blob/main/org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/FileChangeType.java)
The enum in the vscode api uses the following three values: `Changed = 1, Created = 2, Deleted = 3` (see https://code.visualstudio.com/api/references/vscode-api#FileChangeType)

This means that the values of `Created` and `Changed` are incorrect and should actually be the other way around.

**Comment by angelozerr** [comment]
Dont see vscode base code but the lsp support for vscode https://github.com/microsoft/vscode-languageserver-node/blob/main/protocol%2Fsrc%2Fcommon%2Fprotocol.ts#L2213

Lspj follows the spec

**Comment by Papierkorb2292** [comment]
Oh, ok, thank you. I guess I should have checked the protocol first, I apologize.
