### ISSUE TITLE
Build no longer works

### ISSUE THREAD

**Issue by cdietrich** [eclipse-lsp4j/lsp4j#859]
with the jenkins update the centos-7 does no longer work
i am not sure about the gpg hints in deploy-build.sh.

and thus if using ubuntu-2404 would help

**Comment by jonahgraham** [comment]
The gpg info is https://wiki.eclipse.org/Jenkins#How_can_artifacts_be_deployed_to_OSSRH_.2F_Maven_Central.3F - I will add that link to the code for next time.

**Comment by jonahgraham** [comment]
The main branch build is working again - https://ci.eclipse.org/lsp4j/job/lsp4j-multi-build/job/main/ - I think it all deployed correctly too with the gpg update.
